services:
  db:
    image: postgis/postgis:15-3.3
    container_name: saferoute_db
    environment:
      POSTGRES_USER: saferoute_admin
      POSTGRES_PASSWORD: securepassword
      POSTGRES_DB: saferoute_db
    ports:
      - "5432:5432"
    volumes:
      - saferoute_pgdata:/var/lib/postgresql/data

volumes:
  saferoute_pgdata:
