spring:
  application:
    name: saferoute
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/saferoute_db}
    username: ${DATABASE_USER:saferoute_admin}
    password: ${DATABASE_PASSWORD:securepassword}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.spatial.dialect.postgis.PostgisDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

cloudinary:
  cloud_name: ${CLOUDINARY_CLOUD_NAME}
  api_key: ${CLOUDINARY_API_KEY}
  api_secret: ${CLOUDINARY_API_SECRET}
